### ISSUE TITLE
Can`t install curl-client

### ISSUE THREAD

**Issue by funivan** [php-http/curl-client#10]
Hello. I try to install `php-http/curl-client` but it fails
```
composer require php-http/curl-client           
```
```
Using version ^0.3.0 for php-http/curl-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-http/curl-client ^0.3.0 -> satisfiable by php-http/curl-client[v0.3.0].
    - php-http/curl-client v0.3.0 requires php-http/message-factory ^0.4@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

```

**Comment by mekras** [comment]
Try to add this lines to your `composer.json`:

```json
    "prefer-stable": true,
    "minimum-stability": "dev"
```

**Comment by funivan** [comment]
Thanks for fast response. 
But this will change all packages minimum stability version to dev. 
Is there other way to install this package?

**Comment by mekras** [comment]
> But this will change all packages minimum stability version to dev. 

Packages, which has stable versions will not be affected by this setting. See https://getcomposer.org/doc/04-schema.md#prefer-stable

> Is there other way to install this package?

Currently no.

**Comment by funivan** [comment]
Thanks for help @mekras

**Comment by dbu** [comment]
> But this will change all packages minimum stability version to dev.
> Is there other way to install this package?

your only alternative is to explicitly require all dependencies that
have no stable version yet with `@dev`. but you need to list even
indirect dependencies then.

we aim to release a stable first version of the libraries in january.

**Comment by funivan** [comment]
@dbu :+1 wait for stable =)
