### ISSUE TITLE
"Out of memory" sending large files

### ISSUE THREAD

**Issue by jack-theripper** [php-http/curl-client#15]
I'm sending a request method PUT

`Fatal error: Out of memory (allocated 801898496) (tried to allocate 800528777 bytes) in php-http\curl-client\src\Client.php on line 183`

why CURLOPT_POSTFIELDS ?

sample code

```php
$stream = new Stream($file_path, 'rb');
$request = new Request('http://localhost/test.php', 'PUT', $stream);
$response = $client->sendRequest($request);
```

Description PSR-7 Streams written

`Attempting to represent the body of a message as a string can easily consume more memory than intended because the body must be stored completely in memory. Attempting to store the body of a request or response in memory would preclude the use of that implementation from being able to work with large message bodies.`

but Client.php reading full body in variable (in memory). 
what to do?

**Comment by mekras** [comment]
Please try this [Client.php](https://github.com/php-http/curl-client/blob/e3ae04c6146b0f45072648f25a328af5d20f3285/src/Client.php).

**Comment by jack-theripper** [comment]
Проблем с памятью не наблюдается, проверил на разных объемах, Вам удалось пофиксить.
Мне кажется тут есть упущение ибо явно отсутствует передача тела методом PATCH (это одно и тоже что и PUT). Я полагаю нужно заменить 
```php
if (in_array($request->getMethod(), ['OPTIONS', 'POST', 'PUT'], true)) {
```
на
```php
if (in_array($request->getMethod(), ['OPTIONS', 'POST', 'PUT', 'PATCH'], true)) {
```

**Comment by sagikazarmark** [comment]
Please stick to using English so that we can follow what happens. Thank you.

**Comment by mekras** [comment]
> I think there is an omission, there is no transfer of a body by PATCH method. I suppose necessary to replace

Please, create a new issue. I'll check it.
