### ISSUE TITLE
Minimize memory usage when reading large response body

### ISSUE THREAD

**Issue by mekras** [php-http/curl-client#20]

**Comment by mekras** [comment]
Requires https://github.com/php-http/message/pull/40.

**Comment by sagikazarmark** [comment]
Tagged [v1.2.0](https://github.com/php-http/message/tree/v1.2.0)

**Comment by mekras** [comment]
When downloading a 50 MiB file, the peak memory usage is reduced from 198 MiB to 2.22 MiB.

**Comment by dbu** [comment]
> When downloading a 50 MiB file, the peak memory usage is reduced from
> 198 MiB to 2.22 MiB.

wow, massive!

**Comment by mekras** [comment]
Thanks to @jack-theripper.

**Comment by sagikazarmark** [comment]
Nice job :+1:

**Comment by xabbuh** [comment]
What about tagging this also als `1.3.1`? Imo this can safely be treated as a bug fix (as well as the other changes done since the release of `1.3.0`).

**Comment by mekras** [comment]
I thought about it. But the change is pretty significant, actually rewritten the entire stream related part. I think that is a sufficient reason to change the minor version.

**Comment by dbu** [comment]
i agree with that decision, minor versions are ok even when no real new
features are introduced. a minor version means that updating is not
trivial and requires more testing - which is the case here then.
