### ISSUE TITLE
Make discovery a hard dependency

### ISSUE THREAD

**Issue by Nyholm** [php-http/curl-client#25]
Like we did in our other clients and adapters. 

What do you think?

**Comment by mekras** [comment]
Why?

**Comment by Nyholm** [comment]
Because the diacovery is a lightweight package, we do not have to do checks if the discovery exists or not. It may also make the installation/download/bootstrap a bit easier. 

And also, like I said above. All other clients and adapters have a hard dependency or no dependency.

**Comment by mekras** [comment]
Since in fact there is no  actual dependency on discovery, I think it would be better to remove checks from the code.

**Comment by Nyholm** [comment]
Removing these: https://github.com/php-http/curl-client/blob/master/src/Client.php#L85-L90

Will make the constructor arguments non-optional. 

I suggest doing as the Guzzle5 adapter does: https://github.com/php-http/guzzle5-adapter/blob/master/src/Client.php#L40

**Comment by mekras** [comment]
OK.

**Comment by Nyholm** [comment]
You are quick. Thank you!
