### ISSUE TITLE
Add async support to the cURL client

### ISSUE THREAD

**Issue by shulard** [php-http/curl-client#3]
Just found some examples using the `curl_multi_init` the perform async requests here: https://github.com/stil/curl-easy/

The request queue is defined in the file: https://github.com/stil/curl-easy/blob/master/src/cURL/RequestsQueue.php

I think that the idea is here but we can't use the whole logic here. In cURL sync processing and async processing is something different and maybe must be handled in different objects...

If the `curl_reset` function is used in the client, we must ensure that there is no workaround with async mode (see #1).

**Comment by mekras** [comment]
Yea, I know this technique.
