### ISSUE TITLE
PHP 7.2: Failure evaluating code: is_resource($handle)

### ISSUE THREAD

**Issue by samuelnogueira** [php-http/curl-client#36]
In `src/PromiseCore.php:79`, there are 2 assertions as string:
```php
        assert('is_resource($handle)');
        assert('get_resource_type($handle) === "curl"');
```
This behavior is deprecated in PHP 7.2 (see http://php.net/manual/en/function.assert.php).

**Comment by samuelnogueira** [comment]
@mekras I didn't mean to overstep, I just already had a working fix that I would like to share with you and the other contributors if it somehow saves you guys work.

**Comment by Nyholm** [comment]
No worries. I would say this is perfect behavior to write an issue and then create a fix for it. I promise @mekras is super happy that you added a PR.
