### ISSUE TITLE
Support PSR-17 and PSR-18

### ISSUE THREAD

**Issue by Nyholm** [php-http/curl-client#41]
This will drop PHP5 and force us to release a new major version.

**Comment by jmalinens** [comment]
We are waiting for this!

**Comment by mekras** [comment]
This issue depends on https://github.com/php-http/discovery/issues/116

**Comment by Nyholm** [comment]
I’ll put it some work on this during the holidays.

**Comment by dbu** [comment]
psr-18 support has been added in #43, #52 changes to use PSR-17 instead of the httplug message factory.
