### ISSUE TITLE
Seekable and writable stream

### ISSUE THREAD

**Issue by gmponos** [php-http/curl-client#46]
Hello,

How can you be sure that the stream is seekable and writable [here](https://github.com/php-http/curl-client/blob/master/src/Client.php#L141) and [here](https://github.com/php-http/curl-client/blob/master/src/Client.php#L228)?

**Comment by mekras** [comment]
I think we should add isSeekable and isWritable checks.

**Comment by mekras** [comment]
I just looked at the code carefully. We always createstream  inside the method createResponseBuilder. This stream is created for `php: / / temp` with the "w"option. That is, it is always seekable and writable.
