### ISSUE TITLE
curl_strerror and HHVM

### ISSUE THREAD

**Issue by mekras** [php-http/curl-client#6]
MultiRunner class [uses](https://github.com/php-http/curl-client/blob/6dfea603a679717ec9d07a4f2ad1a4a5916fda74/src/MultiRunner.php#L98) function [curl_strerror](http://php.net/curl_strerror), which is [not supported by HHVM](http://docs.hhvm.com/manual/en/function.curl-strerror.php).

**Comment by sagikazarmark** [comment]
We could create a polyfill for it.

**Comment by mekras** [comment]
And how to load it? I have never deal with HHVM.

**Comment by sagikazarmark** [comment]
I would make it a separate repository, something like this: https://github.com/indigophp/hash-compat.

**Comment by dbu** [comment]
in the plugins we said hhvm is not a priority. imho its ok to put hhvm into the allowed failures for the build and add a note in the documentation that this currently does not work with hhvm. 

if you want to make it work, maybe look how guzzle is doing this, if they do at all.
