### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by GrahamCampbell** [php-http/curl-client#68]
This will require some work, since the curl functions no longer return resources.

**Comment by dbu** [comment]
we might want to do a next major version that only works with php 8 then. or wrap resources / the php 8 thing in some abstraction, but that sounds like quite some effort.

**Comment by GrahamCampbell** [comment]
Not necessarily. We should be able to doc resource|CurlHandle. They behave almost the same.

**Comment by ildyria** [comment]
I am sorry to bump the issue, but now that PHP 8 is live. This package becomes one of the blocking for others e.g. https://github.com/geocoder-php/Geocoder

**Comment by GrahamCampbell** [comment]
@ildyria You can prepare a PR of you like.

**Comment by GrahamCampbell** [comment]
I don't see why this should be a blocker for them anyway. They can use any http client, if they are using this curl-client. They should swap out their curl-client dependency for a virtual dependency, so that any http client can be used.

**Comment by dbu** [comment]
geocoder does properly reference the virtual package, but uses curl-client in require-dev for their testing.

but yep, we all agree that it would be useful to do it. now its the question of finding somebody who wants to invest the time to make it happen. i don't have that time right now, but would be happy to review a pull request and can tag the release once its merged.

**Comment by ildyria** [comment]
> @ildyria You can prepare a PR of you like.

Already started working on it this morning, but I don't have the time to dig more (more pressing matters at hand). Nevertheless I used GitHub actions to quickly replicate the behavior of your travis.yml file and quickly start on testing (pretty simple set-up). You can find my finding here:

https://github.com/ildyria/curl-client/actions/runs/391280741
