### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/curl-client#8]
@mekras can you tell me why 0.4 message-factory is required? Ever since the 0.3 release we didn't have a single commit.

I also noticed that both the common psr7 implementations are required in the project. Why is that?

**Comment by mekras** [comment]
> why 0.4 message-factory is required?

It's required by php-http/discovery 0.3

> I also noticed that both the common psr7 implementations are required in the project. Why is that?

Are you talking about guzzle and diactoros? They are used for testing. I have cases, when tests were passed with the one implementation, but fails with the other.

**Comment by sagikazarmark** [comment]
Thanks for clarification.
